# Input the necessary packages

In [1]:
import numpy as np

## check the keras status

In [1]:
import keras

In [2]:
keras.__version__

'2.4.3'

In [3]:
from keras.models import Sequential

In [4]:
from keras.datasets import mnist
from keras.layers import Dense, Dropout, Activation, Flatten

In [5]:
from keras.utils import np_utils # let label transit to 0ne-hot-encoding

In [6]:
from matplotlib import pyplot as plt
import cv2

In [8]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()  # grouping the minst's data to train and test group


In [9]:
print(X_test.shape)  #there are 10000 test images, and the image is in 28 x 28 format

(10000, 28, 28)


In [10]:
print(y_test.shape) # the corresponging number with respect to 10000 images is 10000 as predicted

(10000,)


In [11]:
model = Sequential() # create linear implementing model

In [12]:
model.add(Dense(units=256, input_dim=784, kernel_initializer='normal', activation='relu')) # add input layer and hidden layer

In [13]:
model.add(Dense(units=10, kernel_initializer='normal', activation='softmax')) # add output layer


In [14]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) # Compilation: Choose loss function, optimization method and effectiveness measurement method

In [15]:
y_TrainOneHot = np_utils.to_categorical(y_train)

In [16]:
y_TestOneHot = np_utils.to_categorical(y_test)

In [17]:
X_train_2D = X_train.reshape(60000, 28*28).astype('float32')
X_test_2D = X_test.reshape(10000, 28*28).astype('float32') # 2D-1D

# check the train images

In [18]:
print(X_train.shape) #there are 10000 test images, and the image is in 28 x 28 format

(60000, 28, 28)


In [19]:
print(y_train.shape)

(60000,)


In [20]:
print("X_test_2D: ",X_test_2D.shape)


X_test_2D:  (10000, 784)


In [21]:
print('X_train_2d',X_train_2D.shape)

X_train_2d (60000, 784)


In [22]:
x_Train_norm = X_train_2D/255
x_Test_norm = X_test_2D/255 # important process

In [23]:
scores = model.evaluate(x_Test_norm, y_TestOneHot) #before traing the model

313/313 [==============================] - 0s 451us/step - loss: 2.3352 - accuracy: 0.1338


In [24]:
print("\t[Info] Accuracy of testing data = {:2.1f}%".format(scores[1]*100.0))

	[Info] Accuracy of testing data = 12.8%


In [40]:
X = x_Test_norm[11:20,:]
predictions = model.predict_classes(X)

In [41]:
print(predictions)

[6 9 0 1 5 9 7 3 4]


In [56]:
img=cv2.imread('5.png', cv2.IMREAD_GRAYSCALE)

In [57]:
crop_size = (28, 28)
img = cv2.resize(img, crop_size, interpolation = cv2.INTER_CUBIC)

In [52]:
cv2.imshow('My Image', img)

In [53]:
cv2.waitKey(0)
cv2.destroyAllWindows()


In [58]:
img_2D = img.reshape(1,28*28).astype('float32')
img_norm=img_2D/255
img = img_norm
predictions = model.predict_classes(img)

In [59]:
print(predictions)

[8]


# now we are going to train the data to get model

In [25]:
train_history = model.fit(x=x_Train_norm, y=y_TrainOneHot, validation_split=0.2, epochs=100, batch_size=800, verbose=2)


Epoch 1/100
60/60 - 1s - loss: 0.7823 - accuracy: 0.8169 - val_loss: 0.3231 - val_accuracy: 0.9110
Epoch 2/100
60/60 - 0s - loss: 0.2991 - accuracy: 0.9163 - val_loss: 0.2486 - val_accuracy: 0.9311
Epoch 3/100
60/60 - 0s - loss: 0.2365 - accuracy: 0.9339 - val_loss: 0.2082 - val_accuracy: 0.9439
Epoch 4/100
60/60 - 0s - loss: 0.1949 - accuracy: 0.9459 - val_loss: 0.1776 - val_accuracy: 0.9514
Epoch 5/100
60/60 - 0s - loss: 0.1640 - accuracy: 0.9538 - val_loss: 0.1587 - val_accuracy: 0.9557
Epoch 6/100
60/60 - 0s - loss: 0.1418 - accuracy: 0.9606 - val_loss: 0.1407 - val_accuracy: 0.9610
Epoch 7/100
60/60 - 0s - loss: 0.1231 - accuracy: 0.9660 - val_loss: 0.1296 - val_accuracy: 0.9643
Epoch 8/100
60/60 - 0s - loss: 0.1080 - accuracy: 0.9700 - val_loss: 0.1237 - val_accuracy: 0.9646
Epoch 9/100
60/60 - 0s - loss: 0.0962 - accuracy: 0.9736 - val_loss: 0.1136 - val_accuracy: 0.9678
Epoch 10/100
60/60 - 0s - loss: 0.0859 - accuracy: 0.9763 - val_loss: 0.1070 - val_accuracy: 0.9691
Epoch 11/

Epoch 83/100
60/60 - 0s - loss: 6.6243e-04 - accuracy: 1.0000 - val_loss: 0.0986 - val_accuracy: 0.9784
Epoch 84/100
60/60 - 0s - loss: 6.3800e-04 - accuracy: 1.0000 - val_loss: 0.0990 - val_accuracy: 0.9778
Epoch 85/100
60/60 - 0s - loss: 6.0673e-04 - accuracy: 1.0000 - val_loss: 0.0996 - val_accuracy: 0.9786
Epoch 86/100
60/60 - 0s - loss: 5.8414e-04 - accuracy: 1.0000 - val_loss: 0.0995 - val_accuracy: 0.9784
Epoch 87/100
60/60 - 0s - loss: 5.5816e-04 - accuracy: 1.0000 - val_loss: 0.1005 - val_accuracy: 0.9786
Epoch 88/100
60/60 - 0s - loss: 5.3473e-04 - accuracy: 1.0000 - val_loss: 0.1005 - val_accuracy: 0.9780
Epoch 89/100
60/60 - 0s - loss: 5.2751e-04 - accuracy: 1.0000 - val_loss: 0.1011 - val_accuracy: 0.9782
Epoch 90/100
60/60 - 0s - loss: 4.9011e-04 - accuracy: 1.0000 - val_loss: 0.1015 - val_accuracy: 0.9781
Epoch 91/100
60/60 - 0s - loss: 4.6959e-04 - accuracy: 1.0000 - val_loss: 0.1021 - val_accuracy: 0.9784
Epoch 92/100
60/60 - 0s - loss: 4.5825e-04 - accuracy: 1.0000 - 

In [26]:
scores = model.evaluate(x_Test_norm, y_TestOneHot)

313/313 [==============================] - 0s 432us/step - loss: 0.0893 - accuracy: 0.9804


## after trainging, the accuracy was increased from 0.1358 to  0.9668

In [27]:
print("\t[Info] Accuracy of testing data = {:2.1f}%".format(scores[1]*100.0))


	[Info] Accuracy of testing data = 98.0%


### assess again

In [44]:
img=cv2.imread('4.png', cv2.IMREAD_GRAYSCALE)

In [45]:
crop_size = (28, 28)
img = cv2.resize(img, crop_size, interpolation = cv2.INTER_CUBIC)

In [47]:
img_2D = img.reshape(1,28*28).astype('float32')
img_norm=img_2D/255
img = img_norm
predictions = model.predict_classes(img)

In [48]:
print(predictions)

[5]


In [49]:
train_history = model.fit(x=x_Train_norm, y=y_TrainOneHot, validation_split=0.2, epochs=20, batch_size=800, verbose=2)

Epoch 1/20
60/60 - 0s - loss: 3.1447e-04 - accuracy: 1.0000 - val_loss: 0.1058 - val_accuracy: 0.9783
Epoch 2/20
60/60 - 0s - loss: 3.0796e-04 - accuracy: 1.0000 - val_loss: 0.1060 - val_accuracy: 0.9783
Epoch 3/20
60/60 - 0s - loss: 2.9163e-04 - accuracy: 1.0000 - val_loss: 0.1061 - val_accuracy: 0.9783
Epoch 4/20
60/60 - 0s - loss: 2.8582e-04 - accuracy: 1.0000 - val_loss: 0.1071 - val_accuracy: 0.9787
Epoch 5/20
60/60 - 0s - loss: 2.7019e-04 - accuracy: 1.0000 - val_loss: 0.1066 - val_accuracy: 0.9785
Epoch 6/20
60/60 - 0s - loss: 2.6066e-04 - accuracy: 1.0000 - val_loss: 0.1071 - val_accuracy: 0.9783
Epoch 7/20
60/60 - 0s - loss: 2.5098e-04 - accuracy: 1.0000 - val_loss: 0.1081 - val_accuracy: 0.9782
Epoch 8/20
60/60 - 0s - loss: 2.4453e-04 - accuracy: 1.0000 - val_loss: 0.1082 - val_accuracy: 0.9783
Epoch 9/20
60/60 - 0s - loss: 2.3205e-04 - accuracy: 1.0000 - val_loss: 0.1082 - val_accuracy: 0.9785
Epoch 10/20
60/60 - 0s - loss: 2.2454e-04 - accuracy: 1.0000 - val_loss: 0.1084 - 

In [52]:
train_history = model.fit(x=x_Train_norm, y=y_TrainOneHot, validation_split=0.2, epochs=50, batch_size=800, verbose=2)

Epoch 1/50
60/60 - 0s - loss: 2.0990e-04 - accuracy: 1.0000 - val_loss: 0.1114 - val_accuracy: 0.9783
Epoch 2/50
60/60 - 0s - loss: 2.0170e-04 - accuracy: 1.0000 - val_loss: 0.1123 - val_accuracy: 0.9784
Epoch 3/50
60/60 - 0s - loss: 1.9454e-04 - accuracy: 1.0000 - val_loss: 0.1130 - val_accuracy: 0.9781
Epoch 4/50
60/60 - 0s - loss: 1.8748e-04 - accuracy: 1.0000 - val_loss: 0.1130 - val_accuracy: 0.9783
Epoch 5/50
60/60 - 0s - loss: 1.8257e-04 - accuracy: 1.0000 - val_loss: 0.1139 - val_accuracy: 0.9781
Epoch 6/50
60/60 - 0s - loss: 1.7558e-04 - accuracy: 1.0000 - val_loss: 0.1132 - val_accuracy: 0.9777
Epoch 7/50
60/60 - 0s - loss: 1.6870e-04 - accuracy: 1.0000 - val_loss: 0.1138 - val_accuracy: 0.9780
Epoch 8/50
60/60 - 0s - loss: 1.6157e-04 - accuracy: 1.0000 - val_loss: 0.1145 - val_accuracy: 0.9782
Epoch 9/50
60/60 - 0s - loss: 1.5660e-04 - accuracy: 1.0000 - val_loss: 0.1152 - val_accuracy: 0.9779
Epoch 10/50
60/60 - 0s - loss: 1.5076e-04 - accuracy: 1.0000 - val_loss: 0.1155 - 

In [58]:
img=cv2.imread('6.png', cv2.IMREAD_GRAYSCALE)

In [59]:
crop_size = (28, 28)
img = cv2.resize(img, crop_size, interpolation = cv2.INTER_CUBIC)

In [60]:
img_2D = img.reshape(1,28*28).astype('float32')
img_norm=img_2D/255
img = img_norm
predictions = model.predict_classes(img)

In [61]:
print(predictions)

[2]


In [78]:
train_history = model.fit(x=x_Train_norm, y=y_TrainOneHot, validation_split=0.2, epochs=500, batch_size=800, verbose=2)

Epoch 1/500
60/60 - 0s - loss: 1.8466e-05 - accuracy: 1.0000 - val_loss: 0.1309 - val_accuracy: 0.9795
Epoch 2/500
60/60 - 0s - loss: 1.7711e-05 - accuracy: 1.0000 - val_loss: 0.1313 - val_accuracy: 0.9793
Epoch 3/500
60/60 - 0s - loss: 1.7189e-05 - accuracy: 1.0000 - val_loss: 0.1313 - val_accuracy: 0.9792
Epoch 4/500
60/60 - 0s - loss: 1.6812e-05 - accuracy: 1.0000 - val_loss: 0.1319 - val_accuracy: 0.9796
Epoch 5/500
60/60 - 0s - loss: 1.5959e-05 - accuracy: 1.0000 - val_loss: 0.1322 - val_accuracy: 0.9791
Epoch 6/500
60/60 - 0s - loss: 1.5409e-05 - accuracy: 1.0000 - val_loss: 0.1331 - val_accuracy: 0.9792
Epoch 7/500
60/60 - 0s - loss: 1.4971e-05 - accuracy: 1.0000 - val_loss: 0.1329 - val_accuracy: 0.9794
Epoch 8/500
60/60 - 0s - loss: 1.4359e-05 - accuracy: 1.0000 - val_loss: 0.1334 - val_accuracy: 0.9789
Epoch 9/500
60/60 - 0s - loss: 1.4111e-05 - accuracy: 1.0000 - val_loss: 0.1339 - val_accuracy: 0.9791
Epoch 10/500
60/60 - 0s - loss: 1.3432e-05 - accuracy: 1.0000 - val_loss:

Epoch 80/500
60/60 - 0s - loss: 1.4381e-06 - accuracy: 1.0000 - val_loss: 0.1566 - val_accuracy: 0.9794
Epoch 81/500
60/60 - 0s - loss: 1.3877e-06 - accuracy: 1.0000 - val_loss: 0.1568 - val_accuracy: 0.9795
Epoch 82/500
60/60 - 0s - loss: 1.3511e-06 - accuracy: 1.0000 - val_loss: 0.1574 - val_accuracy: 0.9791
Epoch 83/500
60/60 - 0s - loss: 1.3144e-06 - accuracy: 1.0000 - val_loss: 0.1574 - val_accuracy: 0.9795
Epoch 84/500
60/60 - 0s - loss: 1.2753e-06 - accuracy: 1.0000 - val_loss: 0.1579 - val_accuracy: 0.9795
Epoch 85/500
60/60 - 0s - loss: 1.2510e-06 - accuracy: 1.0000 - val_loss: 0.1581 - val_accuracy: 0.9795
Epoch 86/500
60/60 - 0s - loss: 1.1965e-06 - accuracy: 1.0000 - val_loss: 0.1580 - val_accuracy: 0.9797
Epoch 87/500
60/60 - 0s - loss: 1.1565e-06 - accuracy: 1.0000 - val_loss: 0.1583 - val_accuracy: 0.9799
Epoch 88/500
60/60 - 0s - loss: 1.1304e-06 - accuracy: 1.0000 - val_loss: 0.1589 - val_accuracy: 0.9793
Epoch 89/500
60/60 - 0s - loss: 1.1023e-06 - accuracy: 1.0000 - 

Epoch 159/500
60/60 - 0s - loss: 1.7116e-07 - accuracy: 1.0000 - val_loss: 0.1783 - val_accuracy: 0.9795
Epoch 160/500
60/60 - 0s - loss: 1.6737e-07 - accuracy: 1.0000 - val_loss: 0.1787 - val_accuracy: 0.9797
Epoch 161/500
60/60 - 0s - loss: 1.6220e-07 - accuracy: 1.0000 - val_loss: 0.1789 - val_accuracy: 0.9796
Epoch 162/500
60/60 - 0s - loss: 1.5868e-07 - accuracy: 1.0000 - val_loss: 0.1790 - val_accuracy: 0.9797
Epoch 163/500
60/60 - 0s - loss: 1.5650e-07 - accuracy: 1.0000 - val_loss: 0.1794 - val_accuracy: 0.9796
Epoch 164/500
60/60 - 0s - loss: 1.5228e-07 - accuracy: 1.0000 - val_loss: 0.1796 - val_accuracy: 0.9796
Epoch 165/500
60/60 - 0s - loss: 1.4959e-07 - accuracy: 1.0000 - val_loss: 0.1796 - val_accuracy: 0.9795
Epoch 166/500
60/60 - 0s - loss: 1.4616e-07 - accuracy: 1.0000 - val_loss: 0.1803 - val_accuracy: 0.9797
Epoch 167/500
60/60 - 0s - loss: 1.4248e-07 - accuracy: 1.0000 - val_loss: 0.1805 - val_accuracy: 0.9796
Epoch 168/500
60/60 - 0s - loss: 1.3933e-07 - accuracy:

60/60 - 0s - loss: 4.2908e-08 - accuracy: 1.0000 - val_loss: 0.1934 - val_accuracy: 0.9797
Epoch 238/500
60/60 - 0s - loss: 4.2347e-08 - accuracy: 1.0000 - val_loss: 0.1935 - val_accuracy: 0.9797
Epoch 239/500
60/60 - 0s - loss: 4.1813e-08 - accuracy: 1.0000 - val_loss: 0.1935 - val_accuracy: 0.9797
Epoch 240/500
60/60 - 0s - loss: 4.1408e-08 - accuracy: 1.0000 - val_loss: 0.1938 - val_accuracy: 0.9797
Epoch 241/500
60/60 - 0s - loss: 4.0700e-08 - accuracy: 1.0000 - val_loss: 0.1939 - val_accuracy: 0.9795
Epoch 242/500
60/60 - 0s - loss: 4.0367e-08 - accuracy: 1.0000 - val_loss: 0.1942 - val_accuracy: 0.9796
Epoch 243/500
60/60 - 0s - loss: 3.9756e-08 - accuracy: 1.0000 - val_loss: 0.1944 - val_accuracy: 0.9797
Epoch 244/500
60/60 - 0s - loss: 3.9257e-08 - accuracy: 1.0000 - val_loss: 0.1945 - val_accuracy: 0.9797
Epoch 245/500
60/60 - 0s - loss: 3.8852e-08 - accuracy: 1.0000 - val_loss: 0.1944 - val_accuracy: 0.9797
Epoch 246/500
60/60 - 0s - loss: 3.8331e-08 - accuracy: 1.0000 - val_

Epoch 316/500
60/60 - 0s - loss: 2.0196e-08 - accuracy: 1.0000 - val_loss: 0.2014 - val_accuracy: 0.9797
Epoch 317/500
60/60 - 0s - loss: 2.0020e-08 - accuracy: 1.0000 - val_loss: 0.2015 - val_accuracy: 0.9797
Epoch 318/500
60/60 - 0s - loss: 1.9987e-08 - accuracy: 1.0000 - val_loss: 0.2016 - val_accuracy: 0.9797
Epoch 319/500
60/60 - 0s - loss: 1.9811e-08 - accuracy: 1.0000 - val_loss: 0.2016 - val_accuracy: 0.9796
Epoch 320/500
60/60 - 0s - loss: 1.9652e-08 - accuracy: 1.0000 - val_loss: 0.2017 - val_accuracy: 0.9797
Epoch 321/500
60/60 - 0s - loss: 1.9640e-08 - accuracy: 1.0000 - val_loss: 0.2016 - val_accuracy: 0.9798
Epoch 322/500
60/60 - 0s - loss: 1.9372e-08 - accuracy: 1.0000 - val_loss: 0.2020 - val_accuracy: 0.9797
Epoch 323/500
60/60 - 0s - loss: 1.9307e-08 - accuracy: 1.0000 - val_loss: 0.2020 - val_accuracy: 0.9797
Epoch 324/500
60/60 - 0s - loss: 1.9148e-08 - accuracy: 1.0000 - val_loss: 0.2020 - val_accuracy: 0.9797
Epoch 325/500
60/60 - 0s - loss: 1.8982e-08 - accuracy:

60/60 - 0s - loss: 1.3048e-08 - accuracy: 1.0000 - val_loss: 0.2061 - val_accuracy: 0.9797
Epoch 395/500
60/60 - 0s - loss: 1.2991e-08 - accuracy: 1.0000 - val_loss: 0.2061 - val_accuracy: 0.9797
Epoch 396/500
60/60 - 0s - loss: 1.2959e-08 - accuracy: 1.0000 - val_loss: 0.2062 - val_accuracy: 0.9795
Epoch 397/500
60/60 - 0s - loss: 1.2867e-08 - accuracy: 1.0000 - val_loss: 0.2061 - val_accuracy: 0.9797
Epoch 398/500
60/60 - 0s - loss: 1.2780e-08 - accuracy: 1.0000 - val_loss: 0.2063 - val_accuracy: 0.9798
Epoch 399/500
60/60 - 0s - loss: 1.2731e-08 - accuracy: 1.0000 - val_loss: 0.2063 - val_accuracy: 0.9797
Epoch 400/500
60/60 - 0s - loss: 1.2723e-08 - accuracy: 1.0000 - val_loss: 0.2063 - val_accuracy: 0.9796
Epoch 401/500
60/60 - 0s - loss: 1.2666e-08 - accuracy: 1.0000 - val_loss: 0.2064 - val_accuracy: 0.9797
Epoch 402/500
60/60 - 0s - loss: 1.2527e-08 - accuracy: 1.0000 - val_loss: 0.2064 - val_accuracy: 0.9797
Epoch 403/500
60/60 - 0s - loss: 1.2567e-08 - accuracy: 1.0000 - val_

Epoch 473/500
60/60 - 0s - loss: 9.5492e-09 - accuracy: 1.0000 - val_loss: 0.2091 - val_accuracy: 0.9797
Epoch 474/500
60/60 - 0s - loss: 9.5715e-09 - accuracy: 1.0000 - val_loss: 0.2092 - val_accuracy: 0.9797
Epoch 475/500
60/60 - 0s - loss: 9.5889e-09 - accuracy: 1.0000 - val_loss: 0.2093 - val_accuracy: 0.9797
Epoch 476/500
60/60 - 0s - loss: 9.4548e-09 - accuracy: 1.0000 - val_loss: 0.2093 - val_accuracy: 0.9797
Epoch 477/500
60/60 - 0s - loss: 9.4349e-09 - accuracy: 1.0000 - val_loss: 0.2094 - val_accuracy: 0.9796
Epoch 478/500
60/60 - 0s - loss: 9.4523e-09 - accuracy: 1.0000 - val_loss: 0.2093 - val_accuracy: 0.9798
Epoch 479/500
60/60 - 0s - loss: 9.3828e-09 - accuracy: 1.0000 - val_loss: 0.2094 - val_accuracy: 0.9797
Epoch 480/500
60/60 - 0s - loss: 9.3381e-09 - accuracy: 1.0000 - val_loss: 0.2094 - val_accuracy: 0.9797
Epoch 481/500
60/60 - 0s - loss: 9.2785e-09 - accuracy: 1.0000 - val_loss: 0.2094 - val_accuracy: 0.9797
Epoch 482/500
60/60 - 0s - loss: 9.2834e-09 - accuracy:

In [87]:
X = x_Test_norm[0:10,:]

In [83]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [84]:
predictions = model.predict_classes(X)

In [85]:
print(predictions)

[7 2 1 0 4 1 4 9 6 9]


In [175]:
img=cv2.imread('5.png', cv2.IMREAD_GRAYSCALE)

In [179]:
crop_size = (28, 28)
img = cv2.resize(img, crop_size, interpolation = cv2.INTER_CUBIC)

In [180]:
img_2D = img.reshape(1,28*28).astype('float32')
img_norm=img_2D/255
img = img_norm
predictions = model.predict_classes(img)

In [181]:
print(predictions)

[5]


In [30]:
cv2.imshow("image", img)

In [31]:
cv2.waitKey(0)

-1